### ISSUE TITLE
app.exe with parameters

### ISSUE THREAD

**Issue by sebllll** [BanTheRewind/StayUp#1]
hi,

do you see any way to use your nice tool, if the application needs startup parameters as well?

example:

StayUp MyApp.exe /o "c:\somefile.txt" /anotherparameter -e -i 3600 -t 10

that would be perfect.

thanks anyway for this perfect helper.

//sebl

**Comment by sebllll** [comment]
ai, i found a way:

using a shortcut and adding the parameters in the target field works fine.

e.g.:

target `c:\MyApp.exe /o "c:\somefile.txt" /anotherparameter`

and then simply invoke the script with:
**StayUp MyApp.lnk -e -i 3600 -t 10**

**Comment by BanTheRewind** [comment]
Just woke up and was going to suggest the same thing. That's how I set mine up. Let me know if any other issues arise. 

—
